---
name: idr0048-abdeladim-chroms/experimentA
version: 1

defaults:
  include: no
  type: string
  includeclient: yes
  visible: yes
  omitempty: yes

columns:

  - name: Characteristics [Organism Part]
    clientname: Organism Part
    include: yes

  - name: Characteristics [Strain]
    clientname: Strain
    include: yes

  - name: Reporter
    clientname: Reporter
    include: yes

  - name: Comment [Reporter]
    clientname: Reporter Comment
    include: yes

  - name: Experimental Condition [Genotype]
    clientname: Genotype
    include: yes

  - name: Characteristics [Mouse Age]
    clientname: Mouse Age
    include: yes

  - name: Image Description
    clientname: Image Description
    include: yes

  - name: Channels
    clientname: Channels
    include: yes


  ######################################################################
  # mapr groups
  ######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
        - name: Characteristics [Organism]
          clientname: Organism
          include: yes


advanced:
  ignore_missing_primary_key: yes
  primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
        - Organism
